# Generated by Django 4.2.30 on 2026-04-29 23:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('repuestosfullcars', '0002_alter_categoria_id_alter_producto_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='nombre',
            new_name='nombre_categoria',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='imagen',
            new_name='imagen_url',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='nombre',
            new_name='nombre_producto',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='marca',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='sku',
        ),
        migrations.AddField(
            model_name='categoria',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='categoria',
            name='estado',
            field=models.CharField(default='activo', max_length=10),
        ),
        migrations.AddField(
            model_name='producto',
            name='estado',
            field=models.CharField(default='activo', max_length=10),
        ),
        migrations.AddField(
            model_name='producto',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_compra', models.DateTimeField(auto_now_add=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado_compra', models.CharField(default='pendiente', max_length=20)),
                ('metodo_pago', models.CharField(max_length=50)),
                ('direccion_envio', models.TextField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
